## STAGE 1: Build Angular App ##
FROM node:8 as builder

COPY gov-poc-ng /gov-poc-ng

WORKDIR /gov-poc-ng

RUN npm install
RUN npm install -g @angular/cli
RUN ng build

## STAGE 2: Run nginx to serve application ##
FROM nginx

COPY --from=builder /gov-poc-ng/dist/* /usr/share/nginx/html/

EXPOSE 80